### PR TITLE
Create id_9.0.shp.kml

### PR DESCRIPTION
**Pull request by Asiya-Yunusa**

### CODE REVIEW

**Comment by Asiya-Yunusa** [comment]
Good morning Mofe, please I'm having issues accessing my partner's work. No 381-400. He said you have clarified how to save the documents properly but I still can access them.

**Comment by Mofetoluwa** [comment]
Hi Asiya. That is Kamorudeen right? When you tried opening his file on the Google Earth software, what was it showing on the left panel...where files names show?

**Comment by Asiya-Yunusa** [comment]
Yes, it shows id_384 but as a folder.

**Comment by Mofetoluwa** [comment]
Yeah, I actually spoke to him about it before. He just made a pull request few minutes ago, most likely he has effected the changes. So you can sync your repo and check again.

**Comment by Asiya-Yunusa** [comment]
I can view them now thank you.

**Pull request merged**
