### PR TITLE
Updated Pull Request

### PR DESCRIPTION
**Pull request by Asiya-Yunusa**
Hi Mofe, please is this the proper location?
Thank you.

### CODE REVIEW

**Comment by Mofetoluwa** [comment]
No...they should be saved in grid_annotations >> c2 >> 01 - 21 (Since you're working on 1 to 20)

**Comment by Asiya-Yunusa** [comment]
Please where did I scare it under now?

**Comment by Mofetoluwa** [comment]
You mean the where to save it?

**Comment by Mofetoluwa** [comment]
If you check the directory I mentioned above, you would notice a folder already created for your work. You can save the files in there.

**Pull request closed without merging**
